# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170419_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='numberofpeople',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'numberofpeople'),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'time'),
        ),
    ]
